##################################################
#                                                #
#                                                #
#                  Harry Potter                  #
#                   by iiHeroo                   #
#                                                #
#                                                #
##################################################

#Nothing in here yet :(

wands:
 Blackthorn
 Elder_Wand