name: HarryPotter
version: ${project.version}
author: iiHeroo
main: horrgs.me.org.harrypotter
website: http://www.horrgs.webs.com/
description: Brings a full on Harry Potter experience to your server.
commands:
 hp:
  description: Harry Potter default command.
  alias: [harrypotter, harry_potter, hpotter, harryp]
  